- id: validate-parameter-schema
  name: Validate ROS2 PickNikRobotics Generate Parameter Library Schema
  description: Validates generate_parameter_library YAML files against JSON schema
  entry: schema_validator/validate_schema.py
  language: python
  types: [yaml]
  files: .*parameters\.yaml$
  additional_dependencies: [pyyaml, jsonschema]
